version: "2.4"

services:
  ##db:
    ##container_name: openimis-db
    ##build:
      ##context: ../openimis-db_dkr
      ##args:
       ## - ACCEPT_EULA=${ACCEPT_EULA}
       ## - SA_PASSWORD=${DB_PASSWORD}
       ## - SQL_SCRIPT_URL=${DB_SQL_SCRIPT}
  ##  networks:
    ##  - openimis-net
    ## WARNING:
    ## exposing the database port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
  ##  ports:
  ##   - 1433:1433
  backend:
    platform: linux
    container_name: openimis-backend
    build: 
      context: https://github.com/openimis/openimis-be_py.git#${BE_BRANCH}:/
    command: start
    environment: &backend-env
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REMOTE_USER_AUTHENTICATION=True
      - SITE_ROOT=api
      - CELERY_BROKER_URL=amqp://rabbitmq    
    networks:
      - instant_default
    ## WARNING:
    ## exposing the backend port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
    # ports:
    #  - 8000:8000
    ## OPTION:
    ## if you want to ensure the (demo) db is started prior to backend,
    ## simply add the following dependency
    ##depends_on:
     ## - openimis_db
  rabbitmq:
    container_name: openimis-rabbitmq
    # 3-management is the 3.x version including the admin interface. For a barebones image, use 3-alpine
    image: rabbitmq:3-management
    networks:
      - instant_default
    ## WARNING:
    ## exposing the frontend port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
    ports:
      # Management port, default credentials: guest/guest
      - 15672:15672
      # Other RabbitMQ ports
      - 5672:5672
      - 6379:6379
      - 4369:4369
  worker:
    build: 
      context: https://github.com/openimis/openimis-be_py.git#${BE_BRANCH}:/
    environment: *backend-env
    command: worker
    container_name: openimis-worker
    networks:
      - instant_default
  ibackend:
    container_name: openimis-ibackend
    build: 
      context: https://github.com/openimis/openimis-be_py.git#${BE_BRANCH}:/
    command: start
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REMOTE_USER_AUTHENTICATION=True
      - SITE_ROOT=iapi
    networks:
      - instant_default
    ## WARNING:
    ## exposing the backend port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
    ports:
     - 8000:8000
    ## OPTION:
    ## if you want to ensure the (demo) db is started prior to backend,
    ## simply add the following dependency
    ##depends_on:
     ## - docker_openimis_db
  frontend:
    container_name: openimis-frontend
    build: 
      context: https://github.com/openimis/openimis-fe_js.git#${FE_BRANCH}:/
    mem_limit: 4GB
    command: serve -s build
    environment:
      - REACT_APP_API_URL=/iapi
      - NEW_OPENIMIS_HOST=${NEW_OPENIMIS_HOST}
      - LEGACY_OPENIMIS_HOST=${LEGACY_OPENIMIS_HOST}
    restart: always
    networks:
      - instant_default
    logging:
      driver: "json-file"
#    volumes:
#      - ../conf:/conf
    ## WARNING:
    ## exposing the frontend port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
    # ports:
    #  - 5000:5000
  gateway:
    platform: linux
    container_name: openimis-gateway
    build:
      context: https://github.com/openimis/openimis-gateway_dkr.git#${GW_BRANCH}:/
      shm_size: '4gb'
    environment:
      - NEW_OPENIMIS_HOST=${NEW_OPENIMIS_HOST}
      - LEGACY_OPENIMIS_HOST=${LEGACY_OPENIMIS_HOST}
    volumes:
      - ../conf:/conf
    networks:
      - instant_default
    ports:
      - 1200:80
      - 1300:443
    depends_on:
      - backend
      - ibackend
      - frontend
networks:
  instant_default:
    external:
      name: instant_default
